export const dashboardListColumnLabelMapping: { [key: string]: string } = {
  Tarih: "Tarih",
  Oda: "Oda",
  Pax: "Pax",
  Free: "Free",
  Yetişkin: "Yetişkin",
  Çocuk: "Çocuk",
  "Toplam Kişi": "Toplam Kişi",
  "Yüzde%": "Yüzde%",
  Mevcut: "Mevcut",
  Konum1: "Konum 1",
  Konum2: "Konum 2",
  Konum3: "Konum 3",
  Konum4: "Konum 4",
  Konum5: "Konum 5",
  Konum6: "Konum 6",
  "Konum1%": "Konum 1 %",
  "Konum2%": "Konum 2 %",
  "Konum3%": "Konum 3 %",
  "Konum4%": "Konum 4 %",
  "Konum5%": "Konum 5 %",
  Forecast: "Forecast",
  "Forecast Satılan": "Forecast Satılan",
  "Forecast Kalan": "Forecast Kalan",
  "Son Durum": "Son Durum",
  "Yuzde%(Sondurum)": "Yüzde (Son Durum)",
  "Yuzde%(Net)": "Yüzde (Net)",
  "Mevcut(Net)": "Mevcut (Net)",
  Kalan_1: "Kalan 1",
  Kalan_2: "Kalan 2",
  Kalan_3: "Kalan 3",
  Kalan_4: "Kalan 4",
  Kalan_5: "Kalan 5",
  Kalan_6: "Kalan 6",
  "Gelen Oda": "Gelen Oda",
  "Gelen Yetişkin": "Gelen Yetişkin",
  "Gelen Çocuk": "Gelen Çocuk",
  "Gelen Free": "Gelen Free",
  "Gelen Pax": "Gelen Pax",
  "Gelen Top Kişi": "Gelen Toplam Kişi",
  "Giden Oda": "Giden Oda",
  "Giden Yetişkin": "Giden Yetişkin",
  "Giden Çocuk": "Giden Çocuk",
  "Giden Free": "Giden Free",
  "Giden Pax": "Giden Pax",
  "Giden Toplam Kişi": "Giden Toplam Kişi",
  "Arızalı Oda": "Arızalı Oda",
  "Kapalı Oda": "Kapalı Oda",
  "Yatak(Mevcut)": "Yatak (Mevcut)",
  "Yatak(%)": "Yatak (%)",
  "Doviz Tutar": "Döviz Tutar",
  "Doviz Gerçek": "Döviz Gerçek",
  "TL Gerçek": "TL Gerçek",
  "Brut Tutar": "Brüt Tutar",
  Birleşme: "Birleşme",
  "Birleşme Trace": "Birleşme Trace",
  Stop: "Stop",
  "Yatak%": "Yatak %",
  "Pax(P)": "Pax (P)",
  Bebek: "Bebek",
  "Paxp Yetişkin": "Paxp Yetişkin",
  "Paxp Çocuk": "Paxp Çocuk",
  "Paxp Free": "Paxp Free",
  "Kontenjan Oda": "Kontenjan Oda",
  "Kontenjan Satılan": "Kontenjan Satılan",
  "Kontenjan Kalan": "Kontenjan Kalan",
  "Tentative Oda": "Tentative Oda",
  "Müşteri Tipi(1)": "Müşteri Tipi 1",
  "Müşteri Tipi(2)": "Müşteri Tipi 2",
  "Müşteri Tipi(3)": "Müşteri Tipi 3",
  "Müşteri Tipi(4)": "Müşteri Tipi 4",
  "Müşteri Tipi(5)": "Müşteri Tipi 5",
  "Müşteri Tipi(6)": "Müşteri Tipi 6",
  "Müşteri Tipi(7)": "Müşteri Tipi 7",
  "Müşteri Tipi(8)": "Müşteri Tipi 8",
  "Comp Oda": "Comp Oda",
  "Info Oda": "Info Oda",
  "House Use Oda": "House Use Oda",
  "Net Oda": "Net Oda",
  NoShow: "NoShow",
  "Day Use": "Day Use",
  "Forecasttan Kalan(Tek)": "Forecasttan Kalan (Tek)",
  "Blokajsız Oda": "Blokajsız Oda",
  "Forecast Gelir": "Forecast Gelir",
  "Gun Tarih": "Gün Tarih",
  "Package Tutar": "Package Tutar",
  "Arızalı Toplam": "Arızalı Toplam",
  "Pax(Prm)": "Pax (Prm)",
  "Ort.Pax(Prm)": "Ort. Pax (Prm)",
  "Satılan-Birleşme": "Satılan Birleşme",
  "Pax(Y/C2)": "Pax (Y/C2)",
  His_For: "His For",
  "Otel Kodu": "Otel Kodu",
  "Otel Adı": "Otel Adı",
  Son_Yuzdem: "Son Yüzdem",
  Ort_Oda_Brut: "Ort. Oda Brüt",
  Ort_Paxp_Brut: "Ort. Paxp Brüt",
  Fark_Yuzde: "Fark Yüzde",
  "Package Kdvsiz": "Package KDV'siz",
  "Kdv%": "KDV %",
  "Kon.Vergisi%": "Konaklama Vergisi %",
  "Package Kdv": "Package KDV",
  "Package Kon.Vergisi": "Package Konaklama Vergisi",
  TarihAy: "Tarih Ay",
};
